# Generated by Django 5.0.3 on 2024-03-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_generatedpassword_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedPassword',
        ),
    ]
